version: "3.9"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: ./
      dockerfile: ./php-fpm/Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
      - ../_logs/nginx:/var/log/nginx
    networks:
      - app-network
  node:
    image: node:slim
    container_name: app-node
    tty: true
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - app-network
  mysql:
    image: mysql:8.0.30
    container_name: app-mysql
    restart: always
    environment:
      LANG: en_US.UTF-8  
      LANGUAGE: en_US:en  
      LC_ALL: en_US.UTF-8 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ../_data/mysql:/var/lib/mysql
      - ../_logs/mysql:/var/log/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
